<a href="https://colab.research.google.com/github/vikashkumar97983282-glitch/Deep_Learning/blob/main/BackPropagation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Back Propagation for regression problem

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]],columns=['cgpa','profile_score','lpa'])
df

   cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [3]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [4]:
model = Sequential()

model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation='linear'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [5]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [6]:
model.get_weights()

[array([[ 1.042463  , -0.21233821],
        [-0.66542834, -0.42844188]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.55231994],
        [-0.57374907]], dtype=float32),
 array([0.], dtype=float32)]

In [7]:
new_weights = [np.array([[0.1,0.1],[0.1,0.1]],dtype=np.float32),
               np.array([0.,0.],dtype=np.float32),
               np.array([[0.1],[0.1]],dtype=np.float32),
               np.array([0.],dtype=np.float32)]

In [8]:
model.set_weights(new_weights)

In [9]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [10]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [11]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=75,verbose=1,batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 27.8902
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 27.5895
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 27.2500
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 26.9097
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 26.5600
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 26.2144
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 25.8443
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 25.4320
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 25.0548
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 24.6586
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 24.2605
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 23.8098
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 23.4004
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 22.9301
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 22.4642
Epoch 16/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 22.0436
Epoch 17/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 21.5352
Epoch 18/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 21.0910
Epoch 19/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 20.5447
Epoch 20/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 20.0557
Epoch 21/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 19.6102
Epoch 22/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 19.0528
Epoch 23/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 18.5436
Epoch 24/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 18.0377
Epoch 25/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 17.4972
Epoch 26/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 17.0234
Epoch 27/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 16.4470
Epoch 28/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 15.9250
Epoch 29/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 15.4261
Epoch 30/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 14.8976
Epoch 31/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 14.3847
Epoch 32/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 13.8495
Epoch 33/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 13.3242
Epoch 34/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 12.8137
Epoch 35/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 12.3076
Epoch 36/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 11.7819
Epoch 37/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 11.2965
Epoch 38/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 10.7873
Epoch 39/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 10.3774
Epoch 40/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 9.9170
Epoch 41/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 9.3761
Epoch 42/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 8.9922
Epoch 43/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 8.5750
Epoch 44/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 8.0896
Epoch 45/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.7206
Epoch 46/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7.2637
Epoch 47/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.9133
Epoch 48/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.5431
Epoch 49/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 6.2381
Epoch 50/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.8620
Epoch 51/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.4784
Epoch 52/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 5.1993
Epoch 53/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 4.9323
Epoch 54/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 4.5934
Epoch 55/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 4.3311
Epoch 56/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 4.0800
Epoch 57/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 3.8410
Epoch 58/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 3.6278
Epoch 59/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 3.4474
Epoch 60/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 3.2398
Epoch 61/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 3.0077
Epoch 62/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 2.8702
Epoch 63/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 2.6852
Epoch 64/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 2.5273
Epoch 65/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 2.3795
Epoch 66/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 2.2788
Epoch 67/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 2.1604
Epoch 68/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 2.0109
Epoch 69/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.9149
Epoch 70/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.8473
Epoch 71/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.7453
Epoch 72/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.6733
Epoch 73/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.6225
Epoch 74/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.5559
Epoch 75/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.4936

In [12]:
model.get_weights()

[array([[0.37350425, 0.37350425],
        [0.365547  , 0.365547  ]], dtype=float32),
 array([0.27220818, 0.27220818], dtype=float32),
 array([[0.37282732],
        [0.37282732]], dtype=float32),
 array([0.20467219], dtype=float32)]

Back Propagation for classification problem

In [13]:
df_1 = pd.DataFrame([[8,8,1],[7,9,1],[6,10,0],[5,5,0]],columns=['cgpa','profile_score','lpa'])
df_1

   cgpa  profile_score  lpa
0     8              8    1
1     7              9    1
2     6             10    0
3     5              5    0

In [14]:
model_cls = Sequential()

model_cls.add(Dense(2,activation='sigmoid',input_dim=2))
model_cls.add(Dense(1,activation='sigmoid'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [15]:
model_cls.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [16]:
model_cls.get_weights()

[array([[ 1.068168  , -0.9685298 ],
        [ 0.58845544, -0.5109944 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.72637296],
        [-0.43510687]], dtype=float32),
 array([0.], dtype=float32)]

In [17]:
new_weights_cls = [np.array([[0.1,0.1],[0.1,0.1]],dtype=np.float32),
               np.array([0.,0.],dtype=np.float32),
               np.array([[0.1],[0.1]],dtype=np.float32),
               np.array([0.],dtype=np.float32)]

In [18]:
model.set_weights(new_weights_cls)

In [19]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [20]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='binary_crossentropy',optimizer=optimizer)

In [21]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=75,verbose=1,batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 4.0746
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 3.3681
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 2.7365
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 2.0142
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.3280
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.6038
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: -0.1591
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: -0.8982
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: -1.6392
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: -2.5380
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: -3.6003
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: -4.7037
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: -6.1454
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: -8.0751
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: -11.1626
Epoch 16/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: -17.7768
Epoch 17/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: -64.1280
Epoch 18/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: -71.7407
Epoch 19/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: -71.7407
Epoch 20/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: -71.7407
Epoch 21/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: -71.7407
Epoch 22/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: -71.7407
Epoch 23/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: -71.7407
Epoch 24/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: -71.7407
Epoch 25/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -71.7407
Epoch 26/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: -71.7407
Epoch 27/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: -71.7407
Epoch 28/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: -71.7407
Epoch 29/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: -71.7407
Epoch 30/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: -71.7407
Epoch 31/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: -71.7407
Epoch 32/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: -71.7407
Epoch 33/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -71.7407
Epoch 34/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -71.7407
Epoch 35/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -71.7407
Epoch 36/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -71.7407
Epoch 37/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -71.7407
Epoch 38/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -71.7407
Epoch 39/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: -71.7407
Epoch 40/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -71.7407
Epoch 41/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -71.7407
Epoch 42/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -71.7407
Epoch 43/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -71.7407
Epoch 44/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -71.7407
Epoch 45/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -71.7407
Epoch 46/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -71.7407
Epoch 47/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: -71.7407
Epoch 48/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: -71.7407
Epoch 49/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: -71.7407
Epoch 50/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: -71.7407
Epoch 51/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: -71.7407
Epoch 52/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -71.7407
Epoch 53/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: -71.7407
Epoch 54/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -71.7407
Epoch 55/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: -71.7407
Epoch 56/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: -71.7407
Epoch 57/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: -71.7407
Epoch 58/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: -71.7407
Epoch 59/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: -71.7407
Epoch 60/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: -71.7407
Epoch 61/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: -71.7407
Epoch 62/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: -71.7407
Epoch 63/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: -71.7407
Epoch 64/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: -71.7407
Epoch 65/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: -71.7407
Epoch 66/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: -71.7407
Epoch 67/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: -71.7407
Epoch 68/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: -71.7407
Epoch 69/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: -71.7407
Epoch 70/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: -71.7407
Epoch 71/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: -71.7407
Epoch 72/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: -71.7407
Epoch 73/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: -71.7407
Epoch 74/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: -71.7407
Epoch 75/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: -71.7407